
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN                                
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
       },
       
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN                                
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn
        /* mess: */                                                 
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
         },                   
         { xact: (1,1,0) Myinitvn 
        /* mess: */
            act: 1 Newinivn PlanVN
                 2 PlanVN
                 3 PlanVN
                 4 PlanVN
                 5 PlanVN
                 6 PlanVN
                 7 PlanVN
                 8 PlanVN
                 9 PlanVN
                10 PlanVN 
        /*  val: */   
       };       
       
