import { useState } from "react";
import { ArrowRight, Building2, Layers3, Play, Pause, RotateCcw, SkipForward } from "lucide-react";
import { experimentModel, experimentSummary } from "./MarketExperimentEditor";
import { indexResult, sectorRows, total, position, num, str, ratio, type ExplorerResult, type Row } from "./marketExplorerPresentation";
import { amountText, sectorNames, type Side } from "./seminarPresentation";
import "./MarketModelWorld.css";

const object = (value: unknown): Row => value && typeof value === "object" && !Array.isArray(value) ? value as Row : {};
const rows = (value: unknown): Row[] => Array.isArray(value) ? value as Row[] : [];
const percent = (value: bigint | null) => value === null ? "Nicht definiert" : `${amountText(value)} %`;

export function ModelWorld({ source, valid, onNavigate }: { source: unknown; valid: boolean; onNavigate: (stage: string) => void }) {
  const [selected, setSelected] = useState("strategies");
  const summary = experimentSummary(source), model = experimentModel(source), root = object(source), ict = object(root.ict);
  const sectors = [...new Set(summary.actors.flatMap(a => Object.keys(object(a.sectors))))];
  const layers = [
    { id: "environment", title: "Umwelt & exogene Faktoren", detail: `${summary.events.length} deklarierte Ereignisse`, color: "#ffbf64", items: summary.events.map(e => String(e.kind)), stage: "environment", text: "Äußere Ereignisse sind Annahmen des Experiments. Eintritt, Dauer und Intensität wirken nur über deklarierte Kanäle; eine hypothetische Regulierung ist keine Rechtsprognose." },
    { id: "processes", title: "ICT & Geschäftsvorgänge", detail: `${rows(ict.assets).length} Assets · ${rows(ict.resources).length} Ressourcen · ${rows(ict.services).length} Dienste`, color: "#93a9ff", items: [...new Set(rows(ict.services).map(s => String(s.kind)))], stage: "environment", text: "Vorleistung → Abhängigkeit → verfügbare Arbeitskapazität → FIFO-Vorgang. Antragsbearbeitung beeinflusst wirksame Verträge. Claims/Service bilden administrative Arbeit und Kosten ab; sie verschieben keine Schadenzahlungen." },
    { id: "strategies", title: "Sparten & endogene Strategien", detail: `${summary.families.length} Strategiefamilien · ${sectors.length} deklarierte Sparten`, color: "#32e0dc", items: sectors.map(s => sectorNames[s]), stage: "board", text: "Vorstände bestimmen Parameter und Maßnahmen der Anbieter. Die Nachfrage folgt ihrer eigenen Kundenregel. Strategien werden aus wirksamen Zuordnungen und Maßnahmen ausgeführt; aktuelle VU-Ergebnisse sind keine Information derselben Vorstandsentscheidung." },
    { id: "companies", title: "Unternehmen & Nachfrage", detail: `${summary.actors.length} Modellanbieter · ${summary.customers.length} Kundengruppen`, color: "#74b6ff", items: summary.actors.slice(0,4).map(a => `VU ${a.insurer_id}`), stage: "companies", text: "Modellanbieter tragen getrennte Spartenbücher. Kunden wählen erreichbare Angebote. BaFin-Namen bezeichnen einen Workshop-Referenzfall; Modellbilanzen, Strategien und Provider sind keine erhobenen Unternehmensdaten." },
    { id: "books", title: "Verträge, Bücher & Modellmarkt", detail: "Beiträge · Aufwand · Eigenkapital · Aggregate", color: "#32e0dc", items: ["Verträge", "Buchung", "Marktaggregat"], stage: "results", text: "Nur tatsächliche VU-/Spartenzeilen bilden die Summen. Nicht versicherter Schaden bleibt außerhalb der VU-Bücher. SCR, MCR und regulatorische Solvenzquoten werden im gemeinsamen Markt nicht berechnet." },
  ];
  const layer = layers.find(l => l.id === selected)!;
  return <div data-testid="model-world">
    <div className="model-page-heading"><div><p className="eyebrow">IMS / MODELLWELT</p><h3>Der Markt wird verständlich.</h3><p>Struktur, Zusammenhänge und Grenzen Ihres geladenen Experiments.</p></div><Layers3 size={38} aria-hidden="true"/></div>
    {(summary.reference||summary.shock)&&<p className="model-scope-note">BaFin-Gruppenauswertung 2024 – Workshop: Beiträge einschließlich Ausland und Rückversicherung, redaktionelle Gruppierung ohne Konzerneliminierung. Kein belegter deutscher Direktmarkt. Modellprofile, Strategien und Provider sind Annahmen.</p>}
    {!summary.actors.length ? <div className="experiment-empty"><h4>Zuerst einen Markt laden</h4><button onClick={()=>onNavigate("market")}>Markt wählen</button></div> : <>
      <div className="model-facts"><span>{summary.actors.length} Anbieter</span><span>{sectors.length} Modellsparten</span><span>{summary.periodCount} Perioden</span><span>{valid ? "Vollständige Rechnung geprüft" : "Quelle geladen · Rechnung noch offen"}</span></div>
      <div className="model-split"><figure className="model-world-figure"><figcaption>Struktur des Modellmarkts <small>Perspektivische Strukturansicht · keine räumliche Simulation</small></figcaption>
        <svg viewBox="0 0 900 680" role="group" aria-label="Fünf Ebenen des Rechenkerns: Ebene mit Enter auswählen">
          <defs><linearGradient id="world-plane"><stop stopColor="#244e78" stopOpacity=".94"/><stop offset="1" stopColor="#122743"/></linearGradient></defs>
          {layers.map((l,i)=>{const y=48+i*121;return <g key={l.id} role="button" tabIndex={0} aria-label={`Modellebene ${l.title}`} aria-pressed={selected===l.id} onClick={()=>setSelected(l.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(l.id);}}}>
            <path d={`M120 ${y}H778L840 ${y+54}L78 ${y+54}Z`} fill="url(#world-plane)" stroke={selected===l.id?l.color:"#467397"} strokeWidth={selected===l.id?3:1}/><path d={`M78 ${y+54}L840 ${y+54}V${y+65}H78Z`} fill={l.color} opacity=".2"/>
            <text x="450" y={y+24} textAnchor="middle" fill={l.color} fontSize="21" fontWeight="700">{l.title}</text>
            <text x="450" y={y+48} textAnchor="middle" fill="#e4eefb" fontSize="16">{l.items.slice(0,4).join("   ·   ") || "Kein solcher Kanal deklariert"}</text>
            <text x="450" y={y+95} textAnchor="middle" fill="#bdcde0" fontSize="17">{l.detail}</text>
            {i<4&&<path d={`M450 ${y+99}V${y+116}m-5-5l5 5 5-5`} stroke="#56d5e0" strokeWidth="2" fill="none"/>}
          </g>;})}
        </svg><p>Die Pfeile zeigen den fachlichen Ablauf. Konkrete ICT-Kanten finden Sie in „6 ICT / Prozesse“ nach einer Rechnung.</p></figure>
        <aside className="model-inspector" aria-live="polite"><span className="domain-tag board">MODELLBAUSTEIN</span><h4>{layer.title}</h4><p>{layer.text}</p><dl><dt>Quellenpfad</dt><dd><code>{selected==="environment"?"events / damage_indicators":selected==="processes"?"ict.assets / resources / services":selected==="strategies"?"families / assignments / measures":selected==="companies"?"insurers / customer_groups":"sides.financial_rows"}</code></dd><dt>Modellhorizont</dt><dd>{Number(model.period_count)} Perioden</dd></dl><button className="primary-action" onClick={()=>onNavigate(layer.stage)}>Arbeitsbereich öffnen <ArrowRight size={17} aria-hidden="true"/></button><a href="/api/seminar/handbook/rechenkern.html" target="_blank" rel="noreferrer">Rechenkern und Abweichungen erklären</a></aside>
      </div>
    </>}
  </div>;
}

export function CompanyPortfolio({ source, result, period, side, focus, onFocus, onEdit }: { source: unknown; result: ExplorerResult | null; period: number; side: Side; focus: number; onFocus: (id:number)=>void; onEdit: ()=>void }) {
  const [search,setSearch]=useState(""), [sector,setSector]=useState("total"), [selection,setSelection]=useState<number[]>([]), [page,setPage]=useState(1);
  const summary=experimentSummary(source), actors=summary.actors, current=actors.find(a=>Number(a.insurer_id)===focus)||actors[0];
  const index=result?indexResult(result):null, financial=index?sectorRows(index,side,period,sector):[], positions=position(financial);
  const matches=actors.filter(a=>(sector==="total"||sector in object(a.sectors))&&`${a.name} ${a.insurer_id} ${a.insurance_group_id}`.toLocaleLowerCase("de").includes(search.toLocaleLowerCase("de")));
  const pages=Math.max(1,Math.ceil(matches.length/8)), currentPage=Math.min(page,pages), shown=matches.slice((currentPage-1)*8,currentPage*8);
  const detail=financial.filter(r=>num(r,"insurer_id")===Number(current?.insurer_id)), sums=total(detail);
  const validSelection=selection.filter(id=>actors.some(a=>Number(a.insurer_id)===id));
  function toggle(id:number){setSelection(current=>current.includes(id)?current.filter(n=>n!==id):[...current,id]);}
  return <div data-testid="company-portfolio"><div className="model-page-heading"><div><p className="eyebrow">IMS / UNTERNEHMEN</p><h3>Marktteilnehmer. Eigene Strategien.</h3><p>Unternehmen vergleichen und die Vorstandsentscheidung im gemeinsamen Experiment öffnen.</p></div><Building2 size={38} aria-hidden="true"/></div>
    {(summary.reference||summary.shock)&&<p className="model-scope-note">{result?.scope_notice||"BaFin-Gruppenauswertung 2024 – Workshop: einschließlich Ausland und Rückversicherung; kein belegter deutscher Direktmarkt. Spartenmix, Bilanzen und Strategien sind Modellannahmen."}</p>}
    <div className="model-facts"><span>{actors.length} Modellanbieter</span><span>Fokus: {current?`VU ${current.insurer_id}`:"offen"}</span><span>{validSelection.length} für Anzeigevergleich</span><span>{result?`P${period} · ${result.comparison_labels[side]}`:"Quellenprofil · noch keine Rechenkennzahlen"}</span></div>
    {!current ? <p>Bitte zuerst einen Markt laden.</p> : <div className="model-split portfolio-split"><section className="portfolio-table-panel"><h4>Unternehmensportfolio</h4><div className="portfolio-filters"><label>Unternehmen suchen<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} /></label><label>Portfoliosparte<select value={sector} onChange={e=>{setSector(e.target.value);setPage(1);}}><option value="total">Alle Modellsparten</option>{Object.entries(sectorNames).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label></div><div className="table-scroll" tabIndex={0} role="region" aria-label="Unternehmensportfolio"><table><thead><tr><th>Vergleich</th><th>Unternehmen</th><th>Sparten</th><th>Beiträge</th><th>Modellanteil</th><th>Ergebnis</th></tr></thead><tbody>{shown.map(a=>{const id=Number(a.insurer_id), t=total(financial.filter(r=>num(r,"insurer_id")===id)), p=positions.entries.find(r=>r.aid===id);return <tr key={id} className={Number(current.insurer_id)===id?"portfolio-focus":""}><td><input type="checkbox" aria-label={`VU ${id} für Anzeigevergleich`} checked={validSelection.includes(id)} onChange={()=>toggle(id)}/></td><td><button className="explorer-link" aria-pressed={Number(current.insurer_id)===id} onClick={()=>onFocus(id)}>{String(a.name)}</button><small>VU {id} · {String(a.insurance_group_id)}</small></td><td>{Object.keys(object(a.sectors)).map(s=>sectorNames[s]).join(" / ")}</td><td>{result?amountText(t.premium_income):"Noch nicht gerechnet"}</td><td>{result?percent(p?.share??null):"—"}</td><td>{result?amountText(t.period_profit):"—"}</td></tr>;})}</tbody></table>{!matches.length&&<p>Kein Unternehmen passt zur Auswahl.</p>}</div><nav className="portfolio-pagination" aria-label="Portfolioseiten"><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Zurück</button><span>Seite {currentPage} von {pages} · {shown.length} angezeigte Anbieter</span><button disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Weiter</button></nav><p>{matches.length} von {actors.length} Anbietern · Nenner: alle Anbieter der ausgewählten Sparte, Seite und Periode. Geldwerte in Modellwährung.</p>
    {validSelection.length>0&&<details className="portfolio-comparison" open><summary>Anzeigevergleich · {validSelection.length} Unternehmen</summary><p>Die Auswahl filtert die Anzeige und verändert weder Quelle noch Rechnung.</p>{validSelection.map(id=>{const t=total(financial.filter(r=>num(r,"insurer_id")===id));return <p key={id}><strong>VU {id}</strong> · {result?`Beiträge ${amountText(t.premium_income)} · Ergebnis ${amountText(t.period_profit)} · Eigenkapital ${amountText(t.closing_equity)}`:"Rechenkennzahlen noch offen"}</p>;})}</details>}
    </section><aside className="model-inspector portfolio-inspector"><div className="portfolio-profile-title"><span className="domain-tag board">FOKUSUNTERNEHMEN</span><h4>{String(current.name)}</h4><p>VU {current.insurer_id as number} · {String(current.insurance_group_id)}</p></div><h5>Spartenprofil</h5>{Object.keys(object(current.sectors)).map(s=>{const all=index?sectorRows(index,side,period,"total").filter(r=>num(r,"insurer_id")===Number(current.insurer_id)):[], t=total(all), value=all.find(r=>r.sector_id===s);return <div className="portfolio-sector" key={s}><strong>{sectorNames[s]}</strong><span>{result?percent(ratio(total(value?[value]:[]).premium_income,t.premium_income)):"Deklarierte Modellsparte"}</span></div>;})}<p>{result?`Gebuchte Beiträge als Mixbasis · ${amountText(sums.premium_income)} in der Portfoliosparte.`:"Ein deklarierter Spartenbestand ist kein empirisch erhobener Beitragsmix."}</p><h5>Strategisches Profil</h5>{rows(object(experimentModel(source).assignments).variant).filter(a=>a.insurer_id===current.insurer_id&&Number(a.start)<=6&&Number(a.end)>=6).map(a=><p key={String(a.sector_id)}>{sectorNames[String(a.sector_id)]} · <code>{String(a.family_id)}</code></p>)}<button className="primary-action" onClick={()=>{onFocus(Number(current.insurer_id));onEdit();}}>Strategie bearbeiten <ArrowRight size={17} aria-hidden="true"/></button><p>Wirksame Zuordnung in P6 der Variante; aktuelle Buchungsfamilien stehen in der Auswertung.</p></aside></div>}
  </div>;
}

export function RunReplay({ result, period, playing, onPeriod, onPlaying, onEdit, children }: { result: ExplorerResult|null; period:number; playing:boolean; onPeriod:(p:number)=>void; onPlaying:(p:boolean)=>void; onEdit:()=>void; children:React.ReactNode }) {
  return <section data-testid="run-replay"><div className="model-page-heading"><div><p className="eyebrow">IMS / LAUFANSICHT</p><h3>Marktdynamik im Verlauf.</h3><p>Berechnete Perioden nachvollziehen und eine neue Entscheidungsvariante vorbereiten.</p></div></div>{!result?<div className="experiment-empty"><h4>Zuerst vollständig berechnen</h4><p>Die Laufansicht benötigt das geprüfte Ergebnis des gemeinsamen Experiments.</p></div>:<><div className="replay-notice"><strong>Vollständiger Lauf bereits gerechnet · {result.period_count} Perioden</strong><p>„Abspielen“ und „Pause“ steuern ausschließlich die Anzeige. Es gibt keinen gespeicherten Zwischenstand zum Fortsetzen des Rechenkerns.</p></div><div className="model-facts"><span>Anzeige P{period} von {result.period_count}</span><span>{playing?"Wiedergabe läuft":"Wiedergabe pausiert"}</span><span>Modellnachweis {result.model_result_digest.slice(0,12)}</span></div>{children}<div className="replay-controls"><button className="primary-action" onClick={()=>onPlaying(!playing)} disabled={!playing&&period===result.period_count}>{playing?<Pause size={18} aria-hidden="true"/>:<Play size={18} aria-hidden="true"/>}{playing?"Anzeige pausieren":"Anzeige abspielen"}</button><button onClick={()=>{onPlaying(false);onPeriod(Math.min(result.period_count,period+1));}} disabled={period===result.period_count}><SkipForward size={18} aria-hidden="true"/>Eine Periode weiter</button><button onClick={()=>{onPlaying(false);onPeriod(1);}}><RotateCcw size={18} aria-hidden="true"/>Anzeige auf P1</button></div><label className="replay-slider">Anzeigeperiode · P{period}<input type="range" min={1} max={result.period_count} value={period} onChange={e=>{onPlaying(false);onPeriod(Number(e.target.value));}}/></label><aside className="replay-alternative"><h4>Eine Entscheidung testen</h4><p>Ändern Sie die Vorstandseingaben im selben Experiment. Eine neue vollständige Vergleichsrechnung beginnt in P1; P1–P5 müssen identisch bleiben. Die bisherige Rechnung wird bei einer Eingabeänderung ungültig.</p><button className="secondary-action" onClick={onEdit}>Entscheidungsvariante bearbeiten <ArrowRight size={17} aria-hidden="true"/></button></aside></>}</section>;
}
