import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { amountText, amountUnits, sectorNames, type Side } from "./seminarPresentation";
import { actorsIn, bookTerms, decodeResult, families, fields, ids, indexResult, num, periodRows, position, raw, relevantRows, sectorRows, selectedRows, str, total, type ExplorerResult, type Field, type Row } from "./marketExplorerPresentation";
import "./MarketExplorerWorkbench.css";
import WorkspaceTabs from "./WorkspaceTabs";
import { Activity, ArrowRight, Building2, Globe2, Play, Layers3, Zap, CheckCircle2, Network, Coins, TrendingUp } from "lucide-react";
import { ModelWorld, CompanyPortfolio, RunReplay } from "./MarketModelWorld";
import MarketExperimentEditor, { boardWindowIssue, experimentSummary } from "./MarketExperimentEditor";
import ProviderNetwork from "./ProviderNetwork";

const viewTabs = [{id:"market",label:"1 Verlauf"},{id:"shares",label:"2 Position"},{id:"families",label:"3 Familien"},{id:"flows",label:"4 Wechsel"},{id:"timeline",label:"5 Zeitlinie"},{id:"provider",label:"6 ICT / Prozesse"}];

const choices: Record<string,string> = { us_hyperscaler_outage: "ICT: alle US-Hyperscaler fallen aus", google_motor_entry: "Google kommt in die Kfz-Versicherung", life_demand_shock: "LV wird unattraktiv", dora_2_workshop: "Hypothetische ICT-Umstellung DORA 2.0", bafin: "BaFin-Gruppenauswertung 2024 – Workshop", switch: "Handfall: zwei VUs und wirksamer Wechsel", market: "Handfall: Markt und Strategiefamilien" };
const names = { ...sectorNames, total: "Alle Modellsparten (Geldsummen)" };
const financialNames: Record<Field,string> = { opening_assets: "Anfangsaktiva", opening_liabilities: "Anfangsverpflichtungen", opening_equity: "Anfangs-Eigenkapital", closing_assets: "Schlussaktiva", closing_liabilities: "Schlussverpflichtungen", closing_equity: "Schluss-Eigenkapital", period_profit: "Periodenergebnis", premium_income: "Beiträge", investment_income: "Kapitalanlage", insurance_expense: "Versicherungsaufwand", claims_paid: "Gezahlte Leistungen", operating_expense: "Betriebskosten", measure_cost: "Enthaltene Maßnahmenkosten", capital_contribution: "Kapitalzuführung", capital_distribution: "Ausschüttung" };
const roles = { ceo: { label: "CEO · Position und Ergebnis", view: "shares" }, cio: { label: "CIO · ICT und Wiederanlauf", view: "provider" }, coo: { label: "COO · wirksame Vorgänge", view: "flows" }, cso: { label: "CSO · Strategien und Streuung", view: "families" } };
const pct = (value: bigint | null) => value === null ? "Nicht definiert" : `${amountText(value)} %`;
const numeric = (value: bigint) => Number(value) / 10000;

async function post(path: string, source: unknown) {
  const response = await fetch(`/api/market/${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(source) });
  const body = await response.json();
  if (!response.ok || !body.valid) throw new Error(body.issues?.[0]?.message || "Marktansicht konnte nicht geprüft werden.");
  if (body.content_digest && response.headers.get("etag") !== `"${body.content_digest}"`) throw new Error("Inhaltsnachweis der Marktansicht stimmt nicht.");
  return body;
}
function DataTable({ title, columns, rows }: { title: string; columns: string[]; rows: ReactNode[][] }) {
  return <details className="explorer-table"><summary>{title} · {rows.length} Zeilen</summary><div className="table-scroll" role="region" aria-label={title} tabIndex={0}><table><thead><tr>{columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length && <p>Keine passenden Rechenzeilen in dieser Auswahl.</p>}</div></details>;
}
function Curve({ title, series, period, change, events = [] }: { title: string; series: { label: string; values: number[] }[]; period: number; change: (period: number)=>void; events?: Row[] }) {
  const n = series[0]?.values.length || 1, values = series.flatMap(item=>item.values), min = Math.min(0,...values), max = Math.max(1,...values), span = max-min;
  const x=(p:number)=>54+(p-1)/Math.max(1,n-1)*520, y=(v:number)=>180-(v-min)/span*135;
  return <figure className="explorer-figure"><figcaption>{title}</figcaption><svg viewBox="0 0 620 226" className="explorer-chart" role="slider" tabIndex={0} aria-label={`${title}: Periode wählen mit Pfeiltasten`} aria-valuemin={1} aria-valuemax={n} aria-valuenow={period}
    onKeyDown={e=>{if(e.key === "ArrowLeft" || e.key === "ArrowRight"){e.preventDefault();change(Math.min(n,Math.max(1,period+(e.key==="ArrowRight"?1:-1))));}}}
    onClick={e=>{const box=e.currentTarget.getBoundingClientRect();change(Math.min(n,Math.max(1,Math.round(((e.clientX-box.left)/box.width*620-54)/520*(n-1)+1))));}}>
    {events.map(event=>{const start=num(event,"start_hour")/24+1,end=Math.min(n,start+num(event,"duration_hours")/24);return start<=n && <rect key={str(event,"event_id")} className="explorer-event-window" x={x(start)} y="36" width={Math.max(3,x(end)-x(start))} height="148"/>;})}
    {[0,1,2,3].map(i=><g key={i}><line className="explorer-grid" x1="54" x2="574" y1={y(min+span*i/3)} y2={y(min+span*i/3)}/><text x="48" y={y(min+span*i/3)+4} textAnchor="end">{(min+span*i/3).toLocaleString("de-DE",{maximumFractionDigits:1,notation:"compact"})}</text></g>)}
    {series.map((item,i)=><path key={item.label} className={`explorer-line line-${i}`} d={item.values.map((v,p)=>`${p?"L":"M"}${x(p+1)},${y(v)}`).join(" ")}/>)}
    <line className="explorer-cursor" x1={x(period)} x2={x(period)} y1="34" y2="184"/><text x="54" y="207">P1</text><text x="574" y="207" textAnchor="end">P{n}</text>
  </svg><div className="explorer-legend">{series.map((item,i)=><span key={item.label}><i className={`line-${i}`}/>{item.label}</span>)}{events.length>0 && <span>Schattierung: deklariertes Ereignis</span>}</div><small>Diagrammachsen gerundet; exakte Werte in der Datentabelle. Kurven zeigen Beobachtungen.</small></figure>;
}
function Bars({ title, entries, click }: { title: string; entries: { key: string; label: string; value: bigint | null; minimum?: bigint | null; maximum?: bigint | null }[]; click: (key: string)=>void }) {
  if (!entries.length) return <figure className="explorer-figure"><figcaption>{title}</figcaption><p>Keine auswertbaren Mitglieder in dieser Auswahl.</p></figure>;
  const shown = entries.slice(0,8), values=shown.flatMap(row=>[numeric(row.value || 0n),numeric(row.minimum || 0n),numeric(row.maximum || 0n)]), min=Math.min(0,...values), max=Math.max(1,...values), x=(v:number)=>180+(v-min)/(max-min)*350;
  return <figure className="explorer-figure"><figcaption>{title}</figcaption><svg className="explorer-chart" viewBox={`0 0 600 ${Math.max(100,shown.length*42+42)}`} role="group" aria-label={title}>
    <line className="explorer-grid" x1={x(0)} x2={x(0)} y1="5" y2={shown.length*42+8}/>{shown.map((entry,i)=><g key={entry.key} role="button" tabIndex={0} aria-label={`${entry.label}: ${pct(entry.value)}; Details öffnen`} onClick={()=>click(entry.key)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();click(entry.key);}}}>
      <title>{entry.label}: {pct(entry.value)}</title><text x="8" y={i*42+25}>{entry.label.length>24?entry.label.slice(0,23)+"…":entry.label}</text>
      {entry.value===null?<text x="180" y={i*42+25}>Nicht definiert</text>:<rect className="explorer-bar" x={Math.min(x(0),x(numeric(entry.value)))} y={i*42+10} width={Math.max(2,Math.abs(x(numeric(entry.value))-x(0)))} height="22"/>}
      {entry.minimum!==undefined && entry.minimum!==null && entry.maximum!==undefined && entry.maximum!==null && <line className="explorer-range" x1={x(numeric(entry.minimum))} x2={x(numeric(entry.maximum))} y1={i*42+20} y2={i*42+20}/>}
    </g>)}<text x="180" y={shown.length*42+32}>{min.toLocaleString("de-DE",{maximumFractionDigits:2})} %</text><text x="530" y={shown.length*42+32} textAnchor="end">{max.toLocaleString("de-DE",{maximumFractionDigits:2})} %</text>
  </svg><small>{entries.length>8?`Diagramm zeigt 8 von ${entries.length}; alle Werte in der Tabelle. `:""}Markierung anklicken oder mit Enter öffnen.</small></figure>;
}

export default function MarketExplorerWorkbench() {
  const [caseId,setCaseId]=useState("us_hyperscaler_outage"),[horizon,setHorizon]=useState(25),[source,setSource]=useState<unknown>(null),[result,setResult]=useState<ExplorerResult|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[original,setOriginal]=useState(true);
  const [activeView,setActiveView]=useState("market");
  const [stage,setStage]=useState("market");
  const [playing,setPlaying]=useState(false);
  const [period,setPeriod]=useState(21),[sector,setSector]=useState("total"),[group,setGroup]=useState("market"),[side,setSide]=useState<Side>("variant"),[focus,setFocus]=useState(0),[role,setRole]=useState<keyof typeof roles|"">(""),[asset,setAsset]=useState("portal"),[bookOpen,setBookOpen]=useState(false);
  const revision=useRef(0), sections=useRef<Record<string,HTMLElement|null>>({}), heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{if(result)heading.current?.focus();},[result]);
  useEffect(()=>{if(stage!=="run"||!result||!playing||period>=result.period_count){setPlaying(false);return;}const timer=window.setTimeout(()=>setPeriod(p=>Math.min(result.period_count,p+1)),1100);return()=>window.clearTimeout(timer);},[stage,result,playing,period]);
  useEffect(()=>{const actors=experimentSummary(source).actors;if(actors.length&&!actors.some(a=>Number(a.insurer_id)===focus))setFocus(Number(actors[0].insurer_id));},[source,focus]);
  useEffect(()=>{const navigate=()=>{if(window.location.hash==="#results")setStage("results");};window.addEventListener("hashchange",navigate);return()=>window.removeEventListener("hashchange",navigate);},[]);
  function invalidate(){revision.current++;setResult(null);setError(null);setBookOpen(false);}
  async function act(work:(version:number)=>Promise<void>){const version=revision.current;setBusy(true);setError(null);try{await work(version);}catch(failure){if(version===revision.current)setError(failure instanceof Error?failure.message:"Prüfung fehlgeschlagen.");}finally{if(version===revision.current)setBusy(false);}}
  async function load(){invalidate();setSource(null);await act(async version=>{
    const reference=caseId==="bafin", hand=caseId==="switch"||caseId==="market";
    const body=await post(reference?"reference-case":hand?"workshop-case":"shock-case",reference?{period_count:horizon,workshop:null,overrides:[]} : hand?{case_id:caseId,period_count:horizon,vu_count:caseId==="switch"?2:3}:{case_id:caseId,period_count:horizon});
    if(version===revision.current){setSource(body.shock_bundle||body.source_bundle||body.source_input);setOriginal(true);}
  });}
  async function calculate(){if(!source)return;const issue=boardWindowIssue(source);invalidate();if(issue){setError(issue);return;}await act(async version=>{const body=decodeResult(await post("explore",source));if(version!==revision.current)return;setResult(body);setStage("results");setActiveView(role?roles[role].view:"market");setPeriod(Math.min(21,body.period_count));setSector("total");setGroup("market");setFocus(current=>body.actors.some(a=>a.insurer_id===current)?current:body.actors[0].insurer_id);});}
  function changeSource(next:unknown){invalidate();setSource(next);setOriginal(false);}
  async function readFile(file?:File){if(!file)return;invalidate();setSource(null);if(file.size>16*1024*1024){setError("Analysequelle überschreitet 16 MiB.");return;}await act(async version=>{const next=JSON.parse(await file.text());if(version===revision.current){setSource(next);setOriginal(false);}});}
  async function download(excel:boolean){if(!result||!source)return;await act(async version=>{const digest=result.model_result_digest;const response=await fetch(`/api/market/${excel?"export.xlsx":"source.json"}`,{method:"POST",headers:{"Content-Type":"application/json","If-Match":`"${digest}"`},body:JSON.stringify(excel?{source_input:source,insurer_id:focus}:source)});if(!response.ok||response.headers.get("etag")!==`"${digest}"`)throw new Error("Export benötigt denselben frischen Modellnachweis.");const blob=await response.blob();if(version!==revision.current)return;const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`IMS-AP8-${excel?`VU${focus}`:"Quelle"}-${digest.slice(0,12)}.${excel?"xlsx":"json"}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);});}
  const index=useMemo(()=>result?indexResult(result):null,[result]);
  const view=useMemo(()=>{
    if(!result||!index)return null;
    const all=sectorRows(index,side,period,sector), selected=selectedRows(result,all,group), members=actorsIn(selected);
    const trajectory=Array.from({length:result.period_count},(_,i)=>({period:i+1,baseline:total(selectedRows(result,sectorRows(index,"baseline",i+1,sector),group)),variant:total(selectedRows(result,sectorRows(index,"variant",i+1,sector),group))}));
    const positionAll=position(all),family=families(selected),switches=relevantRows(periodRows(result,side,"switch_rows",period),members,sector),process=relevantRows(periodRows(result,side,"process_rows",period),members,sector);
    const queues=(["baseline","variant"] as Side[]).map(s=>Array.from({length:result.period_count},(_,i)=>{const m=actorsIn(selectedRows(result,sectorRows(index,s,i+1,sector),group));return relevantRows(periodRows(result,s,"process_rows",i+1),m,sector).reduce((sum,row)=>sum+num(row,"closing_queue"),0);}));
    const capacity=(["baseline","variant"] as Side[]).map(s=>Array.from({length:result.period_count},(_,i)=>periodRows(result,s,"resource_rows",i+1).reduce((sum,row)=>sum+amountUnits(str(row,"capacity_work")),0n)));
    return {all,selected,members,trajectory,positionAll,family,switches,process,queues,capacity};
  },[result,index,period,sector,group,side]);
  function jump(viewId:string){if(viewId!=="book")setActiveView(viewId);requestAnimationFrame(()=>{const node=sections.current[viewId];node?.focus();node?.scrollIntoView({block:"start"});});}
  function actorName(id:unknown){if(id===null||id===undefined)return "Nicht versichert";return result?.actors.find(a=>a.insurer_id===Number(id))?.name||`VU ${id}`;}
  function drill(aid:number){setFocus(aid);setBookOpen(true);requestAnimationFrame(()=>jump("book"));}
  function buttonActor(id:unknown){return id===null||id===undefined?"Nicht versichert":<button type="button" className="explorer-link" onClick={()=>drill(Number(id))}>{actorName(id)}</button>;}
  const labels=result?.comparison_labels || {baseline:"Basis",variant:"Variante"};
  const currentTotals=view?view.trajectory[period-1]:null;
  const focusRows=view?.all.filter(row=>num(row,"insurer_id")===focus)||[];
  const bookRows=focusRows, bookBaseline=result&&index?total(sectorRows(index,"baseline",period,sector).filter(row=>num(row,"insurer_id")===focus)):null, bookVariant=result&&index?total(sectorRows(index,"variant",period,sector).filter(row=>num(row,"insurer_id")===focus)):null;
  const dependency=result?periodRows(result,side,"dependency_rows",period).find(row=>row.asset_id===asset):undefined;
  const resource=result?periodRows(result,side,"resource_rows",period):[];
  const events=result?.schedules.events||[];
  const scope=result?.reference;
  const groupLabel=group==="market"?"Gesamter Modellmarkt":group.startsWith("family:")?`Familie · ${result?.families.find(f=>f.family_id===group.slice(7))?.label||group.slice(7)}`:group.startsWith("insurance:")?`Versicherungsgruppe · ${group.slice(10)}`:`Peer · ${result?.peer_groups.find(p=>p.group_id===group.slice(5))?.label||group.slice(5)}`;
  const sourceScope=scope?.source_scope as Row | undefined, sourceRest=scope?.rest as Row | undefined;
  const referenceText=(row:Row|undefined,key:string)=>str(row,key,"Nicht angegeben").replace(".",",");
  const setup=experimentSummary(source);
  return <section className="market-explorer-workbench" data-testid="market-explorer-workbench" aria-labelledby="explorer-title">
    <div className="experiment-banner" hidden={stage!=="market"}><div><p className="eyebrow">IMS / DAS MARKTEXPERIMENT</p><h2 id="explorer-title">Strategien treffen auf Realität.</h2><p>Der Vorstand entscheidet. Die Umwelt verändert sich.<br/>Sehen Sie, wie sich Ihr Markt entwickelt.</p></div><div className="experiment-orbit" aria-hidden="true"><span className="orbit outer"/><span className="orbit inner"/><Globe2 size={82}/><i className="orbit-point board"/><i className="orbit-point environment"/><i className="orbit-point result"/></div></div>
    <div hidden={stage!=="market"} className="experiment-domains" aria-label="Fachlicher IMS-Ablauf"><div><Building2 size={24} aria-hidden="true"/><span>ENDOGEN</span><strong>Vorstand & Strategien</strong><small>Parameter · Maßnahmen · Nachfrageverhalten</small></div><ArrowRight className="domain-arrow" size={22} aria-hidden="true"/><div><Zap size={24} aria-hidden="true"/><span>EXOGEN</span><strong>Umwelt & Ereignisse</strong><small>Schocks · Regulierung · Entwicklungen</small></div><ArrowRight className="domain-arrow" size={22} aria-hidden="true"/><div><Activity size={24} aria-hidden="true"/><span>MODELLWIRKUNG</span><strong>Markt & Geschäft</strong><small>Verträge · Position · Ergebnis · ICT</small></div></div>
    <nav className="experiment-stages" aria-label="Schritte des Marktexperiments">{[{id:"market",label:"Markt wählen",icon:Globe2},{id:"board",label:"Vorstand & Strategien",icon:Building2},{id:"environment",label:"Umwelt & Schocks",icon:Zap},{id:"results",label:"Wirkung verstehen",icon:Activity}].map(({id,label,icon:Icon},i)=><button key={id} type="button" aria-current={stage===id?"step":undefined} onClick={()=>setStage(id)}><span className="stage-number">0{i+1}</span><Icon size={19} aria-hidden="true"/><span>{label}</span></button>)}</nav>
    <nav className="model-explore-nav" aria-label="Modell und Lauf erkunden">{[{id:"world",label:"Modellwelt",icon:Layers3},{id:"companies",label:"Unternehmen",icon:Building2},{id:"run",label:"Laufansicht",icon:Play}].map(({id,label,icon:Icon})=><button key={id} aria-pressed={stage===id} onClick={()=>setStage(id)}><Icon size={18} aria-hidden="true"/>{label}</button>)}<a className="explorer-help" href="/api/seminar/handbook/eingabeinventar.html" target="_blank" rel="noreferrer">Eingaben im Überblick</a></nav>
    {stage!=="market"&&<h2 className="experiment-accessible-heading">{stage==="board"?"Vorstand und Strategien":stage==="environment"?"Umwelt und Schocks":stage==="world"?"Modellwelt":stage==="companies"?"Unternehmen":stage==="run"?"Laufansicht":"Wirkung verstehen"}</h2>}
    <div hidden={stage!=="world"}><ModelWorld source={source} valid={!!result} onNavigate={setStage}/></div>
    <div hidden={stage!=="companies"}><CompanyPortfolio source={source} result={result} period={period} side={side} focus={focus} onFocus={setFocus} onEdit={()=>setStage("board")}/></div>
    <div hidden={stage!=="run"}><RunReplay result={result} period={period} playing={playing} onPeriod={setPeriod} onPlaying={setPlaying} onEdit={()=>setStage("board")}>{result&&view&&<><Curve title="Ausgewählter Schlussrückstand · Anzahl Vorgänge" series={(["baseline","variant"] as Side[]).map((s,i)=>({label:labels[s],values:view.queues[i]}))} period={period} change={setPeriod} events={events}/><ProviderNetwork assets={result.schedules.ict.assets||[]} actual={periodRows(result,side,"dependency_rows",period)} selected={asset} onSelect={setAsset}/><p>P{period} · {labels[side]} · {groupLabel} · {names[sector as keyof typeof names]}. Queue: Anzahl wartender Antrags-, Schaden- und Servicevorgänge; kein gezahlter Schadenbetrag.</p><button className="secondary-action" onClick={()=>{setStage("results");setActiveView("provider");}}>ICT-Wirkung und Buchung erklären</button></>}</RunReplay></div>

    <div hidden={stage!=="market"}>
    <div className="explorer-intro"><div><h3>Ein Markt. Zwei Vergleichsseiten.</h3><p>Öffnen Sie einen erklärten Fall und verfolgen Sie seine Wirkung im gemeinsamen Modellmarkt.</p></div><a className="explorer-help" href="/api/seminar/handbook/market_ap8.html" target="_blank" rel="noreferrer">Anleitung öffnen <ArrowRight size={16} aria-hidden="true"/></a></div>
    <div className="experiment-cases">{[{id:"us_hyperscaler_outage",title:"Wenn die Cloud ausfällt",label:"ICT / RESILIENZ",icon:Network,text:"Gemeinsame Vorleistungen, konkrete Ersatzpfade und wirksame Vorgänge."},{id:"google_motor_entry",title:"Ein neuer Wettbewerber",label:"MARKT / EINTRITT",icon:Building2,text:"Ein fiktiver 41. Anbieter trifft auf bestehende Strategien und Kunden."},{id:"life_demand_shock",title:"Die Nachfrage verändert sich",label:"LEBEN / ENTWICKLUNG",icon:TrendingUp,text:"Neugeschäft unter Druck. Altgarantien bleiben erhalten."},{id:"dora_2_workshop",title:"Neue Rahmenbedingungen",label:"ICT / REGULIERUNG",icon:Layers3,text:"Hypothetischer Workshop-Schock mit Kapazitäts- und Kostenkanal."}].map(({id,title,label,icon:Icon,text})=><button disabled={busy} key={id} aria-pressed={caseId===id} className="experiment-case" onClick={()=>{invalidate();setSource(null);setCaseId(id);}}><Icon size={28} aria-hidden="true"/><small>{label}</small><strong>{title}</strong><span>{text}</span><ArrowRight size={18} className="case-arrow" aria-hidden="true"/></button>)}</div>
    <fieldset disabled={busy} className="explorer-setup"><legend>Ihr Analysefall</legend><div className="explorer-controls">
      <label>Analysefall<select aria-label="Analysefall" value={caseId} onChange={e=>{invalidate();setSource(null);setCaseId(e.target.value);}}>{Object.entries(choices).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
      <label>Analyseperioden<select aria-label="Analyseperioden" value={horizon} onChange={e=>{invalidate();setSource(null);setHorizon(Number(e.target.value));}}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label>
    </div><div className="explorer-actions"><button type="button" className={source?"secondary-action":"primary-action"} onClick={load}>Analysevorlage laden</button>{source!==null && <button type="button" className="secondary-action" onClick={()=>setStage("board")}>Weiter zu den Strategien <ArrowRight size={16} aria-hidden="true"/></button>}</div>
    <details className="explorer-import"><summary>Eigene Analysequelle importieren</summary><label>JSON-Datei auswählen<input aria-label="Eigene Analysequelle importieren" type="file" accept=".json,application/json" onChange={e=>readFile(e.target.files?.[0])}/></label></details></fieldset>
    </div>
    <div hidden={stage!=="board"}><MarketExperimentEditor source={source} original={original} busy={busy} mode="board" actorId={focus} onActor={setFocus} onOwn={()=>changeSource(structuredClone(source))} onChange={changeSource}/></div>
    <div hidden={stage!=="environment"}><MarketExperimentEditor source={source} original={original} busy={busy} mode="environment" onOwn={()=>changeSource(structuredClone(source))} onChange={changeSource}/></div>
    <div className="experiment-runbar"><div>{source!==null ? <><strong data-testid="explorer-source">{original?"Schreibfreie Vorlage geladen":"Eigenes Experiment"}</strong><span>{setup.actors.length} Anbieter · {setup.families.length} Strategiefamilien · {setup.events.length} äußere Ereignisse · {setup.periodCount} Perioden</span></> : <><strong>Ihr Experiment beginnt mit einem Markt.</strong><span>Eine frische Rechnung verbindet Entscheidungen und Umwelt.</span></>}<p className="explorer-next" role="status">{busy?"Prüfung und Berechnung laufen …":result?"Ergebnis bereit · Quelle und Modell sind geprüft.":source?"Quelle bereit · für gültige Ergebnisse frisch berechnen.":"Analysefall wählen und Vorlage laden."}</p></div><button type="button" className="primary-action" disabled={!source||busy} onClick={calculate}><Play size={18} aria-hidden="true"/>Marktansichten frisch berechnen</button></div>
    {busy && <p role="status">Frische Rechnung läuft. Ein vollständiger 100er-Fall und jeder frische Export können mehrere Minuten dauern.</p>}{error && <p role="alert" className="explorer-error">{error}</p>}
    {stage==="results"&&!result&&!busy&&<div className="experiment-empty"><Activity size={38} aria-hidden="true"/><h3>Die Wirkung entsteht im Lauf.</h3><p>{source?"Ihre Entscheidungen und Umweltannahmen sind bereit. Starten Sie die frische Rechnung.":"Wählen Sie zuerst einen Markt und laden Sie seine Quelle."}</p><button className="secondary-action" onClick={()=>setStage("market")}>Zum Markt</button></div>}
    {result&&view&&currentTotals&&<div className="explorer-results" data-testid="explorer-results" hidden={stage!=="results"}>
      <h3 ref={heading} tabIndex={-1}>{result.title}</h3><p className="explorer-note">{result.scope_notice}</p>
      <div className="cockpit-kpis">{[{label:"Gebuchte Beiträge",key:"premium_income" as const,icon:Coins},{label:"Periodenergebnis",key:"period_profit" as const,icon:TrendingUp},{label:"Schluss-Eigenkapital",key:"closing_equity" as const,icon:CheckCircle2},{label:"Betriebskosten",key:"operating_expense" as const,icon:Activity}].map(({label,key,icon:Icon})=><article key={key}><div className="kpi-icon"><Icon size={24} aria-hidden="true"/></div><div><span>{label}</span><strong>{amountText(currentTotals[side][key])}</strong><small>Δ zur Basis {amountText(currentTotals.variant[key]-currentTotals.baseline[key],true)}</small></div></article>)}</div><p className="kpi-context">P{period} · {groupLabel} · {names[sector as keyof typeof names]} · {labels[side]} · Modellwährung. Flüsse dieser Periode, Eigenkapital am Periodenende.</p>
      {scope&&<details data-testid="explorer-reference" className="explorer-note reference-details"><summary>BaFin-Quelle · Ausland und Rückversicherung · deutscher Direktmarkt nicht belegt · Modellprofile sind Workshop-Annahmen</summary><p>BaFin-Referenz: deutsche Direktmarkt-Auswahl {scope.german_direct_selection_verified===true?"belegt":"nicht belegt"}. Modellbeiträge, Bilanzen, Strategien und Provider sind Workshop-Annahmen. Keine realen Unternehmensmarktanteile.</p><p>{str(sourceScope,"notice","")} Quellenjahr {scope.data_year as number}; {scope.candidate_group_count as number} redaktionelle Kandidatengruppen.</p><p>Reste des erfassten Quellenumfangs nach angenommenem Mapping, in Mio. EUR: nicht ausgewählte Gruppen {referenceText(sourceRest,"unselected_groups_million_eur")}; nicht modellierter Anteil der ausgewählten Gruppen {referenceText(sourceRest,"selected_unmodeled_million_eur")}. Diese Reste sind nicht im Modellmarktanteilsnenner enthalten. Modellwährung und Quellen-Euro sind getrennte Einheiten.</p></details>}
      <details className="explorer-proof"><summary>Quellen-, Modell- und Ansichtsnachweis</summary><p>Quelle <code>{result.input_digest}</code></p><p>Modell <code data-testid="explorer-model-digest">{result.model_result_digest}</code></p><p>Ansicht <code>{result.content_digest}</code></p><p>Seed {result.seed}; {result.period_count} vollständige Perioden. Filter ändern diese Nachweise nicht.</p></details>
      <fieldset><legend>Gemeinsame Auswahl für alle sechs Ansichten</legend><div className="explorer-controls">
        <label>Analyseperiode<select aria-label="Analyseperiode" value={period} onChange={e=>setPeriod(Number(e.target.value))}>{Array.from({length:result.period_count},(_,i)=><option key={i+1} value={i+1}>P{i+1}</option>)}</select></label>
        <label>Analysesparte<select aria-label="Analysesparte" value={sector} onChange={e=>setSector(e.target.value)}>{Object.entries(names).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
        <label>Vergleichsgruppe<select aria-label="Vergleichsgruppe" value={group} onChange={e=>setGroup(e.target.value)}><option value="market">Gesamter Modellmarkt</option>{result.families.map(f=><option key={f.family_id} value={`family:${f.family_id}`}>Familie · {f.label} ({sectorNames[f.sector_id]})</option>)}{[...new Set(result.actors.map(a=>a.insurance_group_id))].map(g=><option key={g} value={`insurance:${g}`}>Versicherungsgruppe · {g}</option>)}{result.peer_groups.map(p=><option key={p.group_id} value={`peer:${p.group_id}`}>Peer · {p.label}</option>)}</select></label>
        <label>Vergleichsseite<select aria-label="Vergleichsseite" value={side} onChange={e=>setSide(e.target.value as Side)}><option value="baseline">{labels.baseline}</option><option value="variant">{labels.variant}</option></select></label>
        <label>Fokus-VU<select aria-label="Fokus-VU" value={focus} onChange={e=>setFocus(Number(e.target.value))}>{result.actors.map(a=><option key={a.insurer_id} value={a.insurer_id}>{a.name}</option>)}</select></label>
        <label>Erklärrolle<select aria-label="Erklärrolle" value={role} onChange={e=>{const next=e.target.value as keyof typeof roles;setRole(next);jump(roles[next].view);}}><option value="" disabled>Rollenweg wählen …</option>{Object.entries(roles).map(([id,r])=><option key={id} value={id}>{r.label}</option>)}</select></label>
      </div><label className="explorer-slider">Periodenschieber · P{period}<input type="range" min={1} max={result.period_count} value={period} onChange={e=>setPeriod(Number(e.target.value))}/></label>
      <div className="explorer-jumps">{[1,6,20,21,22,31,100].filter(p=>p<=result.period_count).map(p=><button key={p} aria-pressed={period===p} onClick={()=>setPeriod(p)} aria-label={`Analyse P${p}`}>P{p}</button>)}</div></fieldset>
      <p data-testid="explorer-selection" className="explorer-selection">P{period} · {names[sector as keyof typeof names]} · {groupLabel} · {labels[side]} · {view.members.size} eindeutige ausgewählte VUs. Fokus: {actorName(focus)}{!view.members.has(focus)?" (außerhalb der Vergleichsgruppe)":""}.</p>
      <WorkspaceTabs id="explorer-view" label="Sechs Marktansichten" tabs={viewTabs} selected={activeView} onSelect={id=>{setActiveView(id);setRole("");}} />
      <div className="explorer-grid-layout">
      <div className="explorer-card explorer-wide" ref={node=>{sections.current.market=node;}} tabIndex={-1} data-testid="explorer-market" role="tabpanel" id="explorer-view-panel-market" aria-labelledby="explorer-view-tab-market" hidden={activeView!=="market"}><h4>1 · Markt und Sparten im Verlauf</h4>
        <p>Beiträge und Periodenergebnis sind Flüsse dieser Periode, Eigenkapital ist Schlussbestand. Geldsummen der gewählten VU-/Spartenzeilen.</p>
        <Curve title="Periodenergebnis · Modellwährung" series={(["baseline","variant"] as Side[]).map(s=>({label:labels[s],values:view.trajectory.map(row=>numeric(row[s].period_profit))}))} period={period} change={setPeriod} events={events}/>
        <DataTable title="Exakter Marktverlauf" columns={["Periode",`${labels.baseline}: Beiträge`,`${labels.variant}: Beiträge`,`${labels.baseline}: Ergebnis`,`${labels.variant}: Ergebnis`,"Δ Ergebnis","Δ Schluss-Eigenkapital"]} rows={view.trajectory.map(row=>[<button onClick={()=>setPeriod(row.period)}>P{row.period}</button>,amountText(row.baseline.premium_income),amountText(row.variant.premium_income),amountText(row.baseline.period_profit),amountText(row.variant.period_profit),amountText(row.variant.period_profit-row.baseline.period_profit,true),amountText(row.variant.closing_equity-row.baseline.closing_equity,true)])}/>
        <div className="explorer-metrics"><span>Beiträge <strong data-testid="explorer-selected-premium" data-value={raw(currentTotals[side].premium_income)}>{amountText(currentTotals[side].premium_income)}</strong></span><span>Ergebnis <strong>{amountText(currentTotals[side].period_profit)}</strong></span><span>Schluss-Eigenkapital <strong>{amountText(currentTotals[side].closing_equity)}</strong></span></div>
        <DataTable title="VU- und Spartenbeiträge zum Verlauf" columns={["VU / Buchung","Sparte","Wirksame Familie","Beiträge","Ergebnis","Schluss-Eigenkapital"]} rows={view.selected.map(row=>[buttonActor(row.insurer_id),sectorNames[str(row,"sector_id")],str(row,"family_id"),amountText(str(row,"premium_income")),amountText(str(row,"period_profit")),amountText(str(row,"closing_equity"))])}/>
      </div>
      <div className="explorer-card explorer-wide" ref={node=>{sections.current.shares=node;}} tabIndex={-1} data-testid="explorer-shares" role="tabpanel" id="explorer-view-panel-shares" aria-labelledby="explorer-view-tab-shares" hidden={activeView!=="shares"}><h4>2 · Fokus, Rivalen und Modellmarkt</h4>
        <p>Beitragsanteile nutzen alle Modell-VUs dieser Periode/Sparte als Nenner, auch bei Gruppenausschnitt. Rivalen sind alle übrigen VUs. Gleich hohe Beiträge erhalten denselben Rang.</p>
        <div className="explorer-metrics"><span>Ganzer Nenner <strong data-testid="explorer-denominator" data-value={raw(view.positionAll.denominator)}>{amountText(view.positionAll.denominator)}</strong></span><span>HHI · 0–10.000 <strong data-testid="explorer-hhi" data-value={view.positionAll.hhi===null?"undefined":raw(view.positionAll.hhi)}>{view.positionAll.hhi===null?"Nicht definiert":amountText(view.positionAll.hhi)}</strong></span><span>{view.positionAll.registered} registriert · {view.positionAll.active} aktiv</span></div>
        {view.positionAll.reason&&<p>{view.positionAll.reason}: Anteile, Konzentration und Rang nicht definiert.</p>}
        <Bars title="Gebuchte Modellbeitragsanteile · ausgewählte VUs" entries={view.positionAll.entries.filter(e=>view.members.has(e.aid)).map(e=>({key:String(e.aid),label:actorName(e.aid),value:e.share}))} click={id=>drill(Number(id))}/>
        <div className="table-scroll" role="region" aria-label="Fokus Rivalen Modellmarkt" tabIndex={0}><table data-testid="explorer-position"><thead><tr><th>Vergleich</th><th>Beiträge</th><th>Ergebnis</th><th>Schluss-Eigenkapital</th><th>Anteil</th><th>Position</th></tr></thead><tbody>{[["Fokus",focusRows],["Rivalen",view.all.filter(r=>num(r,"insurer_id")!==focus)],["Modellmarkt",view.all]].map(([label,rows])=>{const values=total(rows as Row[]),entry=view.positionAll.entries.find(e=>e.aid===focus), share=view.positionAll.reason?null:label==="Fokus"?entry?.share??null:label==="Rivalen"?1000000n-(entry?.share||0n):1000000n;return <tr key={String(label)} data-kind={String(label)} data-premium={raw(values.premium_income)}><th>{String(label)}{label==="Fokus"&&<> · {actorName(focus)}</>}</th><td>{amountText(values.premium_income)}</td><td>{amountText(values.period_profit)}</td><td>{amountText(values.closing_equity)}</td><td>{pct(share)}</td><td>{label==="Fokus"?(entry?.rank??(entry?.active===false?"Inaktiv":"Keine Basis")):"—"}</td></tr>;})}</tbody></table></div>
        <p>Jeder Anteil ist einzeln auf vier Stellen gerundet; ihre Summe kann geringfügig von 100 % abweichen. Dies sind Modellwerte.</p>
        <DataTable title="Alle ausgewählten Anteile und Positionen" columns={["VU / Buchung","Beiträge","Anteil am gesamten Modellmarkt","Rang","Aktiv"]} rows={view.positionAll.entries.filter(e=>view.members.has(e.aid)).map(e=>[buttonActor(e.aid),amountText(e.premium),pct(e.share),e.rank??"Nicht definiert",e.active?"Ja":"Nein"])}/>
      </div>
      <div className="explorer-card" ref={node=>{sections.current.families=node;}} tabIndex={-1} data-testid="explorer-families" role="tabpanel" id="explorer-view-panel-families" aria-labelledby="explorer-view-tab-families" hidden={activeView!=="families"}><h4>3 · Strategiefamilien, Streuung und Gewichte</h4>
        <p>Quote = 100 × Periodenergebnis / Anfangsaktiva. Familienmittel gewichtet mit Anfangsaktiva; die dunkle Spanne zeigt gültige Einzelquoten. Null-Anfangsaktiva haben keine individuelle Quote.</p>
        <Bars title="Familienquote und Min/Max · aktuelle Mitglieder" entries={view.family.map(f=>({key:f.fid,label:result.families.find(x=>x.family_id===f.fid)?.label||f.fid,value:f.mean,minimum:f.minimum,maximum:f.maximum}))} click={id=>setGroup(`family:${id}`)}/>
        <DataTable title="Exakte Familiengewichte und Streuung" columns={["Familie auswählen","Mitglieder / Buchung","Anfangsaktiva-Gewicht","Ergebnis","Gewichtete Quote","Minimum","Maximum","Gültige Einzelquoten"]} rows={view.family.map(f=>[<button onClick={()=>setGroup(`family:${f.fid}`)}>{f.fid}</button>,f.members.map(id=><span key={id}>{buttonActor(id)} </span>),amountText(f.totals.opening_assets),amountText(f.totals.period_profit),pct(f.mean),pct(f.minimum),pct(f.maximum),`${f.valid} / ${f.count}`])}/>
        {group.startsWith("family:")&&<p data-testid="explorer-composition">Mitglieder P{period}: Basis {actorsIn(selectedRows(result,sectorRows(index!,"baseline",period,sector),group)).size}; Variante {actorsIn(selectedRows(result,sectorRows(index!,"variant",period,sector),group)).size}. Zusammensetzungsänderungen können mitwirken; kein isolierter Strategieeffekt.</p>}
      </div>
      <div className="explorer-card" ref={node=>{sections.current.flows=node;}} tabIndex={-1} data-testid="explorer-flows" role="tabpanel" id="explorer-view-panel-flows" aria-labelledby="explorer-view-tab-flows" hidden={activeView!=="flows"}><h4>4 · Tatsächlich wirksame Kundenwechsel</h4>
        <p>P1 ist Anfangsbestand. Ein Wechsel zählt erst bei geändertem gültigem Vertragsträger. Nicht versichert bleibt eine eigene Gegenpartei; Kfz- und Sachmengen werden getrennt angezeigt.</p>
        <div className="explorer-flow-map" role="group" aria-label="Wirksame Wechselpfade">{view.switches.slice(0,6).map((row,i)=><div className="explorer-flow" key={i}>{buttonActor(row.previous_insurer_id)}<span>→ {sectorNames[str(row,"sector_id")]} · {amountText(str(row,"quantity"))} →</span>{buttonActor(row.insurer_id)}</div>)}{!view.switches.length&&<p>In dieser Auswahl kein wirksamer Eigentümerwechsel in P{period}.</p>}</div>
        {view.switches.length>6&&<p>{view.switches.length-6} weitere Pfade stehen in der vollständigen Tabelle.</p>}
        <DataTable title="Alle wirksamen Wechsel · keine gemischte Mengensumme" columns={["Kohorte","Sparte","Von","Zu / Buchung","Menge dieser Sparte","Prämie beim gültigen Träger","Beim VU gebuchter Risikoaufwand","Unversicherter Schaden · keine VU-Buchung"]} rows={view.switches.map(row=>[str(row,"group_id"),sectorNames[str(row,"sector_id")],buttonActor(row.previous_insurer_id),buttonActor(row.insurer_id),amountText(str(row,"quantity")),amountText(str(row,"premium_income")),<span data-testid="explorer-vu-risk" data-value={row.insurer_id===null?"0.0000":str(row,"risk_loss")}>{amountText(row.insurer_id===null?"0":str(row,"risk_loss"))}</span>,<span data-testid="explorer-uninsured-risk" data-value={str(row,"uninsured_loss")}>{amountText(str(row,"uninsured_loss"))}</span>])}/>
        {result.clock&&<><p>Bearbeitung in P t und Vertragswirkung frühestens P t+1. Wartende oder nur bearbeitete Anträge sind keine ausgegebenen Policen. Altgarantien bleiben erhalten.</p><DataTable title="Antrags- und Wechselkanal · wirksame Job-IDs" columns={["Job","VU / Buchung","Anfrage","Wirksam","Sparte"]} rows={relevantRows(periodRows(result,side,"switch_process_rows",period),view.members,sector).map(row=>[str(row,"job_id"),buttonActor(row.insurer_id),`P${row.request_period}`,`P${row.effective_period}`,sectorNames[str(row,"sector_id")]])}/><DataTable title="Lebens-Neugeschäft · wirklich ausgegebene Verträge" columns={["Police","Job","VU / Buchung","Anfrage","Ausgabe","Prämie"]} rows={(result.sides[side].life_contract_rows||[]).filter(row=>num(row,"issue_period")===period&&view.members.has(num(row,"insurer_id"))&&(sector==="total"||sector==="life")).map(row=>[str(row,"policy_id"),str(row,"job_id"),buttonActor(row.insurer_id),`P${row.request_period}`,`P${row.issue_period}`,amountText(str(row,"premium"))])}/></>}
      </div>
      <div className="explorer-card explorer-wide" ref={node=>{sections.current.timeline=node;}} tabIndex={-1} data-testid="explorer-timeline" role="tabpanel" id="explorer-view-panel-timeline" aria-labelledby="explorer-view-tab-timeline" hidden={activeView!=="timeline"}><h4>5 · Ereignisse und Entscheidungen im Zeitablauf</h4>
        <p>{result.clock?"Eine Periode umfasst 24 deklarierte Prozessstunden; kein historischer Kalender. Ereignisfenster sind halboffen. ":"Modellperioden ohne angenommene 24-Stunden-ICT-Uhr. "}Die Nachschau zeigt den deklarierten Plan; VUs hatten Vorperiodeninformation, Kunden sahen die aktuellen öffentlichen Angebote.</p>
        <div className="explorer-timeline">{events.filter(event=>ids(event,"insurer_ids").some(id=>view.members.has(id))).map(event=><div key={str(event,"event_id")}><button onClick={()=>setPeriod(Math.min(result.period_count,Math.floor(num(event,"start_hour")/24)+1))}>{str(event,"event_id")} · P{Math.floor(num(event,"start_hour")/24)+1}</button><span> {str(event,"kind")} · Stunden [{str(event,"start_hour")}, {num(event,"start_hour")+num(event,"duration_hours")})</span></div>)}{(result.schedules.responses[side]||[]).filter(response=>ids(response,"insurer_ids").some(id=>view.members.has(id))).map(response=><div key={str(response,"response_id")}><button onClick={()=>setPeriod(Math.min(result.period_count,num(response,"decision_period")))}>Entscheidung {str(response,"response_id")} · P{response.decision_period as number}</button><span> → Vorlauf {response.lead_periods as number} → verfügbar P{num(response,"decision_period")+num(response,"lead_periods")}. Tatsächlicher Effekt folgt Vorgangs-/Preis-/Kostenzeilen.</span></div>)}</div>
        <DataTable title="Tatsächliche Ereigniswirkung in der Periode" columns={["Ereignis","Art","Überlappungsstunden","Kanäle"]} rows={periodRows(result,side,"event_rows",period).filter(row=>ids(row,"insurer_ids").some(id=>view.members.has(id))).map(row=>[str(row,"event_id"),str(row,"kind"),str(row,"overlap_hours"),(row.channels as string[]).join(", ")])}/>
        <DataTable title="Deklarierte Familien- und Maßnahmenzeitfenster" columns={["Typ","VU / Buchung","Sparte","Kennung","Beginn / Entscheidung","Ende / Vorlauf"]} rows={[...result.schedules.assignments[side].filter(row=>view.members.has(num(row,"insurer_id"))&&(sector==="total"||row.sector_id===sector)).map(row=>["Familie",buttonActor(row.insurer_id),sectorNames[str(row,"sector_id")],str(row,"family_id"),`P${row.start}`,row.end===null?"Bis Laufende":`P${row.end}`]),...result.schedules.measures[side].filter(row=>view.members.has(num(row,"insurer_id"))&&(sector==="total"||row.sector_id===sector)).map(row=>["Maßnahme",buttonActor(row.insurer_id),sectorNames[str(row,"sector_id")],str(row,"measure_id"),`Entscheidung P${row.decision_period}`,`${row.lead_periods} Perioden Vorlauf; Dauer ${row.duration}`])]}/>
        <DataTable title="Wirksame Strategieentscheidungen" columns={["VU / Buchung","Sparte","Familie / Regel","Parameter","Maßnahmen","VU-Information"]} rows={view.selected.map(row=>[buttonActor(row.insurer_id),sectorNames[str(row,"sector_id")],`${row.family_id} / ${row.rule}`,JSON.stringify(row.parameters),JSON.stringify(row.active_measures),`P${row.information_period}`])}/>
        <DataTable title="Konkrete Kostenbuchungen · bereits in Betriebskosten" columns={["Kosten-ID","VU / Buchung","Sparte","Betrag","Grund"]} rows={relevantRows(periodRows(result,side,"cost_rows",period),view.members,sector).map(row=>[str(row,"cost_id"),buttonActor(row.insurer_id),sectorNames[str(row,"sector_id")],amountText(str(row,"amount")),str(row,"explanation","")])}/>
      </div>
      <div className="explorer-card explorer-provider" ref={node=>{sections.current.provider=node;}} tabIndex={-1} data-testid="explorer-provider" role="tabpanel" id="explorer-view-panel-provider" aria-labelledby="explorer-view-tab-provider" hidden={activeView!=="provider"}><h4>6 · ICT-Abhängigkeiten, Rückstand und Wiederanlauf</h4>
        {result.clock?<><p className="explorer-impact">Der gemeinsame Providergraph und die Ressourcenbudgets sind Gesamtkontext. Die Vorgangs-Queues folgen der VU-/Spartenauswahl. Ersatz ist nur mit geprüftem konkretem Pfad wirksam; ein gemeinsames US-IAM bleibt sichtbar.</p>
          <ProviderNetwork assets={result.schedules.ict.assets||[]} actual={periodRows(result,side,"dependency_rows",period)} selected={asset} onSelect={setAsset}/>
          <div className="explorer-provider-map" role="group" aria-label="Deklarierter Providergraph">{(result.schedules.ict.assets||[]).map(node=>{const actual=periodRows(result,side,"dependency_rows",period).find(r=>r.asset_id===node.asset_id),lost=amountUnits(str(actual,"lost_equivalent_hours"));return <button key={str(node,"asset_id")} className={`explorer-provider-node ${lost>0n?"failed":""}`} aria-pressed={asset===node.asset_id} onClick={()=>setAsset(str(node,"asset_id"))}><strong>{str(node,"asset_id")}</strong><span>{str(node,"label")}</span><span>Kontrolle {str(node,"control")} · {amountText(lost)} verlorene Stunden</span><span>→ {(node.depends_on as string[]).join(" → ")||"keine erklärte Vorleistung"}</span></button>;})}</div>
          <div className="explorer-path-proof" data-testid="explorer-path-proof"><strong>Konkreter Pfad {asset} · P{period}</strong><p>Transitiv: {((dependency?.transitive_path as string[])||[]).join(" → ")||"keine weitere deklarierte Abhängigkeit"}. Ursachen: {((dependency?.causing_event_ids as string[])||[]).join(", ")||"kein aktiver Ereignisbeleg"}. Unbekannte Kontrolle ist kein Beleg für unabhängigen Ersatz.</p>{resource.map(row=><details key={str(row,"resource_id")}><summary>{str(row,"resource_id")} · tatsächliche Ersatz-/Kapazitätssegmente</summary><pre>{JSON.stringify({fallback:row.fallback_segments,capacity:row.capacity_segments},null,2)}</pre></details>)}</div>
          <div className="explorer-dual"><Curve title="Gemeinsames Budget · Arbeitseinheiten, einmal je Ressourcenpool" series={(["baseline","variant"] as Side[]).map((s,i)=>({label:labels[s],values:view.capacity[i].map(numeric)}))} period={period} change={setPeriod} events={events}/><Curve title="Ausgewählter Schlussrückstand · Anzahl Vorgänge" series={(["baseline","variant"] as Side[]).map((s,i)=>({label:labels[s],values:view.queues[i]}))} period={period} change={setPeriod} events={events}/></div>
          <DataTable title="Gemeinsame Ressourcen · keine Zuteilung je VU" columns={["Pool","Budget Arbeitseinheiten","Bearbeitete Arbeit","Gesamt-Queue Vorgänge","Verlorene Äquivalentstunden"]} rows={resource.map(row=>[str(row,"resource_id"),amountText(str(row,"capacity_work")),amountText(str(row,"processed_work")),num(row,"closing_queue"),amountText(str(row,"lost_equivalent_hours"))])}/>
          <DataTable title="Ausgewählte Verwaltungs- und Antragsqueues" columns={["Prozess","VU / Buchung","Sparte","Art","Anfangsqueue","Zugänge","Bearbeitet","Schlussqueue"]} rows={view.process.map(row=>[str(row,"service_id"),buttonActor(row.insurer_id),sectorNames[str(row,"sector_id")],str(row,"kind"),num(row,"opening_queue"),num(row,"arrivals"),num(row,"completed"),num(row,"closing_queue")])}/>
          <DataTable title="Konkrete bearbeitete Jobs · Zeitpunkt und spätere Vertragswirkung" columns={["Job","VU / Buchung","Sparte","Art","Anfrage","Bearbeitet","Prozessstunde","Vertrag wirksam"]} rows={relevantRows((result.sides[side].job_rows||[]).filter(row=>num(row,"completed_period")===period),view.members,sector).map(row=>[str(row,"job_id"),buttonActor(row.insurer_id),sectorNames[str(row,"sector_id")],str(row,"kind"),`P${row.created_period}`,`P${row.completed_period}`,str(row,"completed_hour"),row.contract_effective_period===null?"Verwaltung":`P${row.contract_effective_period}`])}/>
          <DataTable title="Vorgangs- und Wiederanlaufverlauf · genaue Daten" columns={["Periode","Basis Budget","Variante Budget","Basis ausgewählte Queue","Variante ausgewählte Queue"]} rows={view.trajectory.map((row,i)=>[<button onClick={()=>setPeriod(row.period)}>P{row.period}</button>,amountText(view.capacity[0][i]),amountText(view.capacity[1][i]),view.queues[0][i],view.queues[1][i]])}/>
          <p>Claims/Service koppeln administrative Arbeit und Kosten. Versicherungszahlungen werden dadurch nicht verzögert. Kein SCR/MCR-, Storno-, Insolvenz- oder Complianceurteil.</p>
        </>:<p>Dieser Fall deklariert keinen ICT-/Prozesskanal. Es werden keine Providerbeziehungen oder Kapazitäten erfunden.</p>}
      </div>
      </div>
      <section className="explorer-book" ref={node=>{sections.current.book=node;}} tabIndex={-1} aria-label="Konkrete Modellbuchung"><h4>Buchungsnachweis · {actorName(focus)} · P{period} · {names[sector as keyof typeof names]}</h4><button onClick={()=>setBookOpen(!bookOpen)} aria-expanded={bookOpen}>{bookOpen?"Buchungsdetails schließen":"Konkrete Buchungsdetails öffnen"}</button>
      {bookOpen&&bookBaseline&&bookVariant&&<div data-testid="explorer-book"><p>Arithmetische Zerlegung Δ = Variante minus Basis. Keine isolierte Ursache. Maßnahmen-/Prozesskosten sind bereits in Betriebskosten; gezahlte Leistungen werden nicht doppelt abgezogen.</p><div className="table-scroll" role="region" aria-label="Exakte Eigenkapitalbrücke" tabIndex={0}><table><thead><tr><th>Gebuchter Term</th><th>Basis</th><th>Variante</th><th>Beitrag zu Δ Schluss-Eigenkapital</th></tr></thead><tbody>{bookTerms.map(term=><tr key={term.key} data-term={term.key} data-value={raw(term.sign*(bookVariant[term.key]-bookBaseline[term.key]))}><th>{term.label}</th><td>{amountText(bookBaseline[term.key])}</td><td>{amountText(bookVariant[term.key])}</td><td>{amountText(term.sign*(bookVariant[term.key]-bookBaseline[term.key]),true)}</td></tr>)}<tr data-term="closing_equity" data-value={raw(bookVariant.closing_equity-bookBaseline.closing_equity)}><th>Exakte Summe = Δ Schluss-Eigenkapital</th><td>{amountText(bookBaseline.closing_equity)}</td><td>{amountText(bookVariant.closing_equity)}</td><td>{amountText(bookVariant.closing_equity-bookBaseline.closing_equity,true)}</td></tr></tbody></table></div><DataTable title="Alle konkreten VU-Spartenbuchungen der gewählten Seite" columns={["Sparte","Quelle / Regel","Parameter",...fields.map(f=>financialNames[f])]} rows={bookRows.map(row=>[sectorNames[str(row,"sector_id")],`${row.source_contract} / ${row.rule}`,JSON.stringify(row.parameters),...fields.map(f=>amountText(str(row,f)))])}/><p>Modellkanal: deklarierte Ereignis-/Abhängigkeit → tatsächliche Ressource/Vorgang → wirksamer Vertrag → Kosten/Prämie/Risiko in diesen Buchungen. Kosten- und Job-IDs stehen in Zeitlinie und Prozessansicht. Zusammenspiel ist kein isolierter Schockanteil.</p></div>}
      </section><p className="explorer-note">{result.causal_limit}</p><div className="explorer-jumps"><button disabled={busy} onClick={()=>download(false)}>Analysequelle frisch als JSON exportieren</button><button disabled={busy} onClick={()=>download(true)}>Fokus-VU frisch als Excel exportieren</button></div>
    </div>}
  </section>;
}
